version: "3.9"
services:
  api:
    build: ./backend
    ports: ["8000:8000"]

  web:
    build: ./frontend
    ports: ["5173:80"]
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
