import librosa
import numpy as np
import torch

from app.config import settings
from app.scoring.audio_features import extract_features


MODEL = None  # plug in real model later


def evaluate_audio(path: str):
    audio, sr = librosa.load(path, sr=16000)
    seconds = len(audio) / 16000.0

    if settings.USE_DUMMY_SCORING or MODEL is None:
        norm = np.clip(seconds / 10.0, 0, 1)
        if norm > 0.8:
            level = "C1"
            explanation = "Highly fluent, clear, and cohesive speech."
            recommendations = (
                "- Extend answers with more detail.\n"
                "- Incorporate more advanced vocabulary.\n"
                "- Continue refining fluency and coherence."
            )
        elif norm > 0.6:
            level = "B2"
            explanation = "Generally fluent with some hesitations."
            recommendations = (
                "- Use more precise vocabulary.\n"
                "- Add more connectors.\n"
                "- Practice developing longer answers."
            )
        elif norm > 0.4:
            level = "B1"
            explanation = "Can express basic ideas but with limited range."
            recommendations = (
                "- Improve sentence structure.\n"
                "- Expand vocabulary.\n"
                "- Practice speaking for longer without pausing."
            )
        else:
            level = "A2"
            explanation = "Short, simple responses with frequent pauses."
            recommendations = (
                "- Practice everyday topics.\n"
                "- Use simple sentence patterns.\n"
                "- Increase speaking confidence gradually."
            )

        return {
            "level": level,
            "explanation": explanation,
            "recommendations": recommendations,
            "seconds": seconds,
        }

    # model path (future)
    features = extract_features(audio, sr)
    with torch.no_grad():
        prediction = torch.sigmoid(features.mean()).item()

    if prediction > 0.8:
        level = "C1"
    elif prediction > 0.6:
        level = "B2"
    elif prediction > 0.4:
        level = "B1"
    else:
        level = "A2"

    return {
        "level": level,
        "explanation": "Score generated by CEFR model (placeholder).",
        "recommendations": "Model-based recommendations unavailable yet.",
        "seconds": seconds,
    }
